// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QcpuqlpRFgJRptnFb3WZiNB2qNdwm2A',
    appId: '1:59959695061:web:03a22dd426aedd3cfd745c',
    messagingSenderId: '59959695061',
    projectId: 'utaxi-f6ec7',
    authDomain: 'utaxi-f6ec7.firebaseapp.com',
    storageBucket: 'utaxi-f6ec7.appspot.com',
    measurementId: 'G-H9LE2HRT04',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyyTqgDTyKJf96us_RUjkE0fQbJ10elI',
    appId: '1:59959695061:ios:07b08ee0be646011fd745c',
    messagingSenderId: '59959695061',
    projectId: 'utaxi-f6ec7',
    storageBucket: 'utaxi-f6ec7.appspot.com',
    iosBundleId: 'com.example.utaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyyTqgDTyKJf96us_RUjkE0fQbJ10elI',
    appId: '1:59959695061:ios:07b08ee0be646011fd745c',
    messagingSenderId: '59959695061',
    projectId: 'utaxi-f6ec7',
    storageBucket: 'utaxi-f6ec7.appspot.com',
    iosBundleId: 'com.example.utaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4QcpuqlpRFgJRptnFb3WZiNB2qNdwm2A',
    appId: '1:59959695061:web:03a22dd426aedd3cfd745c',
    messagingSenderId: '59959695061',
    projectId: 'utaxi-f6ec7',
    authDomain: 'utaxi-f6ec7.firebaseapp.com',
    storageBucket: 'utaxi-f6ec7.appspot.com',
    measurementId: 'G-H9LE2HRT04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOtugmpysu-zDhNM1O6IsG9wn-q4nHQg',
    appId: '1:59959695061:android:04505e1f981c5494fd745c',
    messagingSenderId: '59959695061',
    projectId: 'utaxi-f6ec7',
    storageBucket: 'utaxi-f6ec7.appspot.com',
  );

}